#!/usr/bin/env python3
"""
PureScan Command Sheet Generator
=================================
Generates a printable HTML page with QR codes for all PureScan control codes.
Can be run standalone: python generate_command_sheet.py > command_sheet.html

Requires: pip install qrcode[pil]
If qrcode is not available, generates a text-only fallback.
"""

import html
import sys

# ── Control codes ──────────────────────────────────────────────────────────
COMMANDS = [
    # Actions
    {'code': 'SYS:TRANSFER',  'label': 'Transfer Stock',    'icon': '🔄', 'color': '#f59e0b'},
    {'code': 'SYS:INFO',      'label': 'Info / Lookup',     'icon': 'ℹ️',  'color': '#3b82f6'},
    {'code': 'SYS:ADD',       'label': 'Add Stock',         'icon': '➕', 'color': '#10b981'},
    {'code': 'SYS:REMOVE',    'label': 'Remove Stock',      'icon': '➖', 'color': '#ef4444'},
    {'code': 'SYS:STOCKTAKE', 'label': 'Stocktake',         'icon': '📋', 'color': '#8b5cf6'},
    {'code': 'SYS:CANCEL',    'label': 'Cancel / Reset',    'icon': '❌', 'color': '#64748b'},
    {'code': 'SYS:UNDO',      'label': 'Undo Last',         'icon': '↩️',  'color': '#f59e0b'},
    # Quantities
    {'code': 'SYS:QTY:1',     'label': 'Quantity: 1',       'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:5',     'label': 'Quantity: 5',       'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:10',    'label': 'Quantity: 10',      'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:25',    'label': 'Quantity: 25',      'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:50',    'label': 'Quantity: 50',      'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:100',   'label': 'Quantity: 100',     'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:250',   'label': 'Quantity: 250',     'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:500',   'label': 'Quantity: 500',     'icon': '#',  'color': '#6b7280'},
    {'code': 'SYS:QTY:1000',  'label': 'Quantity: 1000',    'icon': '#',  'color': '#6b7280'},
]


def generate_qr_svg(text: str, box_size: int = 4) -> str:
    """Generate an inline SVG QR code for the given text."""
    try:
        import qrcode
        import qrcode.image.svg
        qr = qrcode.QRCode(
            version=1, error_correction=qrcode.constants.ERROR_CORRECT_M,
            box_size=box_size, border=2,
        )
        qr.add_data(text)
        qr.make(fit=True)
        factory = qrcode.image.svg.SvgPathImage
        img = qr.make_image(image_factory=factory)
        svg_bytes = img.to_string()
        return svg_bytes.decode('utf-8')
    except ImportError:
        # Fallback: large text
        return f'<div style="font-size:1.2rem;font-weight:700;padding:1rem;word-break:break-all">{html.escape(text)}</div>'


def generate_html() -> str:
    cards_html = []
    for cmd in COMMANDS:
        qr = generate_qr_svg(cmd['code'])
        cards_html.append(f'''
        <div class="card">
            <div class="qr">{qr}</div>
            <div class="label" style="color:{cmd['color']}">
                <span class="icon">{cmd['icon']}</span> {html.escape(cmd['label'])}
            </div>
            <div class="code">{html.escape(cmd['code'])}</div>
        </div>''')

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PureScan – Command Sheet</title>
<style>
@page {{ margin: 1cm; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 2rem; background: #fff; color: #1e293b; }}
h1 {{ text-align: center; font-size: 1.5rem; margin-bottom: .25rem; }}
.subtitle {{ text-align: center; color: #64748b; margin-bottom: 2rem; font-size: .9rem; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr)); gap: 1rem; }}
.card {{ border: 2px solid #e2e8f0; border-radius: 10px; padding: 1rem; text-align: center; break-inside: avoid; }}
.qr {{ display: flex; justify-content: center; margin-bottom: .75rem; }}
.qr svg {{ width: 120px; height: 120px; }}
.label {{ font-weight: 700; font-size: .95rem; margin-bottom: .2rem; }}
.icon {{ font-style: normal; }}
.code {{ font-family: 'Courier New', monospace; font-size: .75rem; color: #94a3b8; }}
.footer {{ text-align: center; margin-top: 2rem; font-size: .75rem; color: #94a3b8; }}
@media print {{
    body {{ padding: .5cm; }}
    .grid {{ gap: .5rem; }}
    .card {{ padding: .5rem; }}
}}
</style>
</head>
<body>
<h1>🎯 PureScan – Command Sheet</h1>
<p class="subtitle">Scan any code below to trigger the corresponding action in the PureScan Terminal</p>
<div class="grid">{"".join(cards_html)}</div>
<p class="footer">Generated by Smart Parts Plugin – Print this sheet and place at warehouse workstations</p>
</body>
</html>'''


if __name__ == '__main__':
    output = generate_html()
    if len(sys.argv) > 1 and sys.argv[1] not in ('-',):
        with open(sys.argv[1], 'w', encoding='utf-8') as f:
            f.write(output)
        print(f'Command sheet saved to: {sys.argv[1]}', file=sys.stderr)
    else:
        print(output)
